 Volume in drive C has no label.
 Volume Serial Number is 6AFD-38FA

 Directory of c:\gittest

10/03/2017  03:09 PM    <DIR>          .
10/03/2017  03:09 PM    <DIR>          ..
10/03/2017  03:09 PM    <DIR>          KAUSHIK
10/03/2017  02:52 PM    <DIR>          NOSGOTH
10/03/2017  11:04 AM    <DIR>          TestFldr1
               0 File(s)              0 bytes
               5 Dir(s)  160,576,987,136 bytes frees
               I am making changes
               asdfaff
